### ISSUE TITLE
Can you support Japanese?

### ISSUE THREAD

**Issue by johmaru** [kevinmussi/iTunes-Discord-RP#8] opened 2019-04-10 01:55 UTC
Hello, I'm Japanese.
I am using a translation now.
It is quick, but Japanese is garbled.

As in this picture
![c90eb8d89d159ea0d64e4eecb3a02049](https://user-images.githubusercontent.com/21039159/55845994-13a40000-5b7f-11e9-9da2-f3e329e5bab8.png)

It will be saved if you fix it.

**Comment by Tomoli75** [comment] 2019-09-15 12:13
The app was intended to run in English, by the looks of it.
Wait until @kevinmussi adds language files (may be never).

**Comment by kevinmussi** [comment] 2020-01-12 14:42
Sorry for the very late response but I didn't catch this problem initially because Japanese text worked fine for me on Mac, so it was just a Windows issue. Anyway, now it should be fixed in [version 1.3](https://github.com/kevinmussi/iTunes-Discord-RP/releases/tag/1.3).

**Closed** 2020-01-15 10:30 UTC
Labels: bug
